# Generated by Django 5.2.6 on 2025-10-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='prescripcion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='prescripcion',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosis_recomendada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='duracion',
            field=models.CharField(default='7 dias', max_length=50),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='frecuencia',
            field=models.CharField(default='1 vez al dia', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='dosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='medicamento',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
